### ISSUE TITLE
Go Live Checklist

### ISSUE THREAD

**Issue by keithmancuso** [familiar-studio/bigduck#63]
Social Media
- [x] Make sure facebook “og:" meta tags are all setup properly and verify with linter 
- [x] Setup twitter card meta tags and verify
- [ ] Setup facebook “app” through the facebook developers portal and add app:id to SEOMATIC
- [ ] Make sure to setup a default “facebook image transform” 470px by 246px

Performance testing
- [ ] Run site through website grader score should be in the 90's
- [ ] Run site through google page speed insights 

Code Review
- [x] Setup humans.txt file based on our familiar humans.txt starter
- [x] Ensure default meta tags title, author
- [x] Make sure 404 page is setup properly and working
- [x] Ensure favicon setup and working at various sizes
- [ ] Setup apple touch icon at various sizes
- [x] Check html guidelines from html5 boilerplate
- [ ] Verify Key site pages print reasonably and add/update a print style sheet as needed
- [ ] Add Familiar ASCII art to the top of layout
- [ ] Check all image tags and ensure they have proper alt tags
- [ ] Mark up key meta data based on guides from google. Special attention should be paid to events, products and news/blog posts
- [x] Disable any development only or unused plugins
- [ ] Review copy throughout site and ensure there is no lingering lorem ispum or other placeholder text

Forge\Server Setup
- [ ] Ensure max execution time in php set to at least 300 to prevent stuck tasks based on this guide
- [ ] Set max upload size to atleast 20mb in forge under “meta”
- [ ] Setup default domain in nginx using a redirect (either with or without www) based on this gist
- [ ] Setup site SSL to run though https either through Cloudflare or LetsEncrypt

Google Search Console
https://www.google.com/webmasters/tools/home?hl=en
- [ ] Verify site including www. and root domains
- [ ] Connect search console to google analytics
- [ ] Setup preferred domain name in settings
- [ ] Setup and submit automated sitemap.xml using a plugin like this one
- [ ] Update and verify robots.txt to unblock google
- [ ] Setup any page updating query parameters

Google Analytics
- [ ] Ensure google analytics code is setup and only runs in production (not on local machine)
- [ ] Setup social media event tracking for any like/tweet buttons
- [ ] Make an annotation for launch day  on timeline
- [ ] Setup any key conversions as goals in google analytics

External Systems Setup
- [ ] Setup Uptime Monitoring through Pingdom
- [ ] Add Site to bugsnag and install tracking code
